In [1]:
%cd ..
%pip install -e .

/home/sandor/dtu/2021-22-spring/advanced_machine_learning/p-reg
Obtaining file:///home/sandor/dtu/2021-22-spring/advanced_machine_learning/p-reg
  Preparing metadata (setup.py) ... done
  Attempting uninstall: src
    Found existing installation: src 0.1.0
    Uninstalling src-0.1.0:
      Successfully uninstalled src-0.1.0
  Running setup.py develop for src
Note: you may need to restart the kernel to use updated packages.


In [2]:
import torch
from torch_geometric.data import Data
from src.models.train_model import compute_a


In [12]:
x = torch.tensor([
    [1,2,3],
    [0,0,0],
    [2,3,2],
    [4,3,2]],
    dtype=torch.float)

edge_index = torch.tensor([
    [0,1],
    [0,2],
    [0,3],
    [2,3],])
data = Data(x=x, edge_index=edge_index.T)

print(data.x)

tensor([[1., 2., 3.],
        [0., 0., 0.],
        [2., 3., 2.],
        [4., 3., 2.]])


In [19]:
A = compute_a(data)
D = torch.diag(A.sum(dim=0))
A_hat = D.inverse()@A
print(A)
print('-----------------------------')
print(data.x)
print((A_hat@data.x))

tensor([[0., 1., 1., 1.],
        [1., 0., 0., 0.],
        [1., 0., 0., 1.],
        [1., 0., 1., 0.]])
-----------------------------
tensor([[1., 2., 3.],
        [0., 0., 0.],
        [2., 3., 2.],
        [4., 3., 2.]])
tensor([[2.0000, 2.0000, 1.3333],
        [1.0000, 2.0000, 3.0000],
        [2.5000, 2.5000, 2.5000],
        [1.5000, 2.5000, 2.5000]])


In [21]:
print(A_hat)

tensor([[0.0000, 0.3333, 0.3333, 0.3333],
        [1.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.0000, 0.0000, 0.5000],
        [0.5000, 0.0000, 0.5000, 0.0000]])
